# Generated by Django 5.2.6 on 2025-09-26 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcard', verbose_name='Product Card'),
        ),
        migrations.CreateModel(
            name='CartLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcard', verbose_name='Product Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart Line Item',
                'verbose_name_plural': 'Cart Line Items',
            },
        ),
    ]
